allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
minimumReleaseAgeExclude:
  - '@sokol111/ecommerce-catalog-service-api@1.2.2'
  - '@sokol111/ecommerce-image-service-api@1.2.2'
overrides:
  '@sokol111/ecommerce-catalog-service-api': link:../ecommerce-catalog-service-api/gen/typescript
  '@sokol111/ecommerce-image-service-api': link:../ecommerce-image-service-api/gen/typescript
